"""add r2 storage columns

Revision ID: 1c6f2d686103
Revises: 0001_create_dataset_records
Create Date: 2026-02-06 01:17:49.962385

"""
from alembic import op
import sqlalchemy as sa


revision = '1c6f2d686103'
down_revision = '0001_create_dataset_records'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_records', sa.Column('storage_provider', sa.Text(), nullable=True))
    op.add_column('dataset_records', sa.Column('object_key', sa.Text(), nullable=True))
    op.add_column('dataset_records', sa.Column('bytes', sa.BigInteger(), nullable=True))
    op.add_column('dataset_records', sa.Column('mime', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_records', 'mime')
    op.drop_column('dataset_records', 'bytes')
    op.drop_column('dataset_records', 'object_key')
    op.drop_column('dataset_records', 'storage_provider')
    # ### end Alembic commands ###
